# Generated by Django 4.2 on 2024-08-27 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_followings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followings',
        ),
    ]
