# Generated by Django 4.2 on 2024-08-26 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_article_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='like_count',
        ),
    ]
