# Generated by Django 5.1 on 2024-08-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_article_like_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='hashtag', to='products.hashtag'),
        ),
    ]
