# Generated by Django 5.1 on 2024-08-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_article_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='articles',
            field=models.ManyToManyField(related_name='hashtag_articles', to='products.article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='article_hashtags', to='products.hashtag'),
        ),
    ]
