# Generated by Django 5.1 on 2024-08-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_hashtag_articles_alter_article_hashtags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='articles',
            field=models.ManyToManyField(related_name='article_hashtags', to='products.article'),
        ),
    ]
