# Generated by Django 5.1 on 2024-08-26 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_hashtag_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='articles',
        ),
        migrations.CreateModel(
            name='ArticleHashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.article')),
                ('hashtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.hashtag')),
            ],
        ),
    ]
