# Generated by Django 5.1 on 2024-08-26 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_hashtag_articles_articlehashtag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleHashtag',
        ),
    ]
